Document: imagick-svg-php
Title: Debian imagick-svg-php Manual
Author: <insert document author here>
Abstract: This manual describes what imagick-svg-php is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/imagick-svg-php/imagick-svg-php.sgml.gz

Format: postscript
Files: /usr/share/doc/imagick-svg-php/imagick-svg-php.ps.gz

Format: text
Files: /usr/share/doc/imagick-svg-php/imagick-svg-php.text.gz

Format: HTML
Index: /usr/share/doc/imagick-svg-php/html/index.html
Files: /usr/share/doc/imagick-svg-php/html/*.html
